### ISSUE TITLE
Error on interactive run

### ISSUE THREAD

**Issue by sreekarchigurupati** [mistralai/mistral-inference#14]
Running the code in this manner
```bash
python -m main interactive /path/mistral-7B-v0.1/
```

It gives the following error
```bash
Prompt: Traceback (most recent call last):
  File "/N/soft/sles15/deeplearning/Python-3.10.9/Lib/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/N/soft/sles15/deeplearning/Python-3.10.9/Lib/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/N/project/grg_data/projects/LLMs/mistral/mistral-src/main.py", line 134, in <module>
    fire.Fire({
  File "/N/u/srchig/BigRed200/.local/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/N/u/srchig/BigRed200/.local/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/N/u/srchig/BigRed200/.local/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/N/project/grg_data/projects/LLMs/mistral/mistral-src/main.py", line 110, in interactive
    res, _logprobs = generate([prompt], transformer, tokenizer, max_tokens)
  File "/N/u/srchig/BigRed200/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
TypeError: generate() takes 3 positional arguments but 4 were given
```

**Comment by lucuss21** [comment]
I think First, you have to run Python as your user (say ~joe or whatever your UID is) but then you bring sudo to the table. And that's where things starts to differ, because it will not inherit your environment. Simple test for you to replay (substitute python3 by whatever path/ best version you want): thank you

**Comment by Victoire21** [comment]
I would like to know Why when I run this code : "!python -m main interactive /content/mistral-7B-v0.1/" The result is : "^C". How to resolve it?

**Comment by Victoire21** [comment]
@sreekarchigurupati : 

As I know, there are two files involved : tokenizer.model and param.json found inside mistral-7B-v0.1 folder.
In your main.py", line 110,  generate([prompt], transformer, tokenizer, max_tokens) asked for 3 arguments. 
This is the actual main.py Line 110 code: 
"        prompt = input("Prompt: ")
        res, _logprobs = generate(
            [prompt],
            transformer,
            tokenizer,
            max_tokens=max_tokens,
            temperature=temperature,
        )"
It show 4 arguments : transformer, tokenizer, max_tokens and temperature. So try to download the actuated folder.

**Comment by Victoire21** [comment]
Hi @arthurmensch, @alexandresablayrolles 

![image](https://github.com/mistralai/mistral-src/assets/139128209/59d05389-a99d-437d-805a-92d939ebd2a2)
J'ai essayé de débugger en utilisant pdb. J'ai remarqué que le répertoire de python recherché est : /usr/local/lib/python3.10/. 
Ma question est la suivante: est-il possible de tester Mistral AI sur colab ou devrais-je obligatoirement utiliser un environnement linux? Si oui, est-ce que cette erreur n'est pas dû au fait qu'il y a des fonctionnalités python qui ne sont pas prise en compte. Merci de votre réponse.
Bonne journée!!

**Comment by juliendenize** [comment]
Hi! We're archiving this repository as it's no longer actively maintained, and therefore this issue is being closed.
