### ISSUE TITLE
[BUG: Cannot build on Mac M1 Silicion

### ISSUE THREAD

**Issue by timspannzilliz** [mistralai/mistral-inference#224]
### Python -VV

```shell
Note: This error originates from the build backend, and is likely not a problem with poetry but with xformers (0.0.26.post1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "xformers (==0.0.26.post1)"'.
```

### Pip Freeze

```shell
(milvusvenv) (base) timothyspann@tspannmac mistral-inference % pip freeze
absl-py==2.1.0
accelerate==0.33.0
aiofiles==24.1.0
aiohappyeyeballs==2.4.0
aiohttp==3.10.5
aiolimiter==1.1.0
aiosignal==1.3.1
airllm==2.9
alembic==1.13.2
altair==5.4.1
annotated-types==0.6.0
anthropic==0.28.1
antlr4-python3-runtime==4.9.3
anyio==4.4.0
appdirs==1.4.4
appnope==0.1.4
argcomplete==3.5.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
arxiv==2.1.3
asgiref==3.8.1
assemblyai==0.26.0
astra-assistants==2.1.0.18
astrapy==1.4.1
asttokens==2.4.1
async-lru==2.0.4
asyncer==0.0.5
attrs==24.2.0
audioread==3.0.1
Authlib==1.3.2
azure-core==1.30.1
azure-storage-blob==12.20.0
Babel==2.15.0
backoff==2.2.1
bce-python-sdk==0.9.21
bcrypt==4.0.1
beautifulsoup4==4.12.3
bidict==0.23.1
bitsandbytes==0.42.0
black==21.4b2
bleach==6.1.0
blinker==1.8.2
blis==0.7.11
bokeh==3.4.3
boto3==1.34.162
botocore==1.34.162
breadability==0.1.20
Brotli==1.1.0
bs4==0.0.2
build==1.2.1
cachetools==5.5.0
cassandra-driver==3.29.1
cassio==0.1.8
catalogue==2.0.10
cattrs==24.1.0
certifi==2024.8.30
cffi==1.16.0
chameleon @ git+https://github.com/facebookresearch/chameleon.git@dbbe47fdbc7a3cc4982ae931fea75e227262e70a
chardet==5.2.0
charset-normalizer==3.3.2
chroma-hnswlib==0.7.3
chromadb==0.4.24
chunkit==0.2.8
clevercsv==0.8.2
click==8.1.7
clip @ git+https://github.com/openai/CLIP.git@a1d071733d7111c9c014f024669f959182114e33
cloudpathlib==0.18.1
cloudpickle==3.0.0
cohere==5.9.0
colorama==0.4.6
colorcet==3.1.0
coloredlogs==15.0.1
colorlog==6.8.2
comm==0.2.2
composio_core==0.5.13
composio_langchain==0.5.13
confection==0.1.5
contourpy==1.2.1
coolname==2.2.0
crewai==0.36.1
crewai-tools==0.4.26
cryptography==42.0.7
cycler==0.12.1
cymem==2.0.8
dacite==1.7.0
dataclasses-json==0.6.5
datacommons-pandas==0.0.3
datasets==3.0.0
debugpy==1.8.1
decorator==5.1.1
deepdiff==7.0.1
defusedxml==0.7.1
Deprecated==1.2.14
deprecation==2.1.0
detectron2 @ git+https://github.com/facebookresearch/detectron2.git@82a57ce0b70057685962b352535147d9a8118578
dill==0.3.8
dirtyjson==1.0.8
discord.py==2.4.0
diskcache==5.6.3
distro==1.9.0
dnspython==2.6.1
docker==7.1.0
docopt==0.6.2
docstring_parser==0.16
docx2txt==0.8
dspy-ai==2.4.14
duckdb==1.0.0
e2b==0.17.2a52
e2b-code-interpreter==0.0.10
easyocr==1.7.1
ecdsa==0.19.0
einops==0.8.0
elastic-transport==8.15.0
elasticsearch==8.15.0
email_validator==2.2.0
embedchain==0.1.121
emoji==2.12.1
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl#sha256=86cc141f63942d4b2c5fcee06630fd6f904788d2f0ab005cce45aadb8fb73889
encodec==0.1.1
environs==9.5.0
et-xmlfile==1.1.0
executing==2.0.1
faiss-cpu==1.8.0.post1
fake-useragent==1.5.1
Faker==28.4.1
fastapi==0.111.0
fastapi-cli==0.0.4
fastavro==1.9.5
fastjsonschema==2.19.1
feedparser==6.0.11
fiftyone==0.24.1
fiftyone-brain==0.16.1
fiftyone-desktop==0.34.1
fiftyone_db==1.1.5
filelock==3.16.0
filetype==1.2.0
firecrawl-py==0.0.16
-e git+https://github.com/FlagOpen/FlagEmbedding.git@399d12f3e238f7d5c82c86939691f195041e0159#egg=FlagEmbedding
FLAML==2.2.0
Flask==3.0.3
Flask-SocketIO==5.3.6
flatbuffers==24.3.25
fonttools==4.51.0
fqdn==1.5.1
frozendict==2.4.4
frozenlist==1.4.1
fsspec==2024.6.1
ftfy==6.2.3
funcy==2.0
future==1.0.0
fvcore==0.1.5.post20221221
geomet==0.2.1.post1
gitdb==4.0.11
GitPython==3.1.43
glob2==0.7
google-ai-generativelanguage==0.6.6
google-api-core==2.19.2
google-api-python-client==2.143.0
google-auth==2.34.0
google-auth-httplib2==0.2.0
google-auth-oauthlib==1.2.1
google-cloud-aiplatform==1.64.0
google-cloud-bigquery==3.25.0
google-cloud-core==2.4.1
google-cloud-resource-manager==1.12.5
google-cloud-storage==2.18.2
google-crc32c==1.6.0
google-generativeai==0.7.2
google-resumable-media==2.7.2
google_search_results==2.4.2
googleapis-common-protos==1.65.0
gotrue==2.8.0
gptcache==0.1.44
gql==3.5.0
grandalf==0.8
graphql-core==3.2.3
greenlet==3.0.3
groq==0.11.0
grpc-google-iam-v1==0.13.1
grpcio==1.63.0
grpcio-health-checking==1.62.3
grpcio-status==1.62.3
grpcio-tools==1.62.3
gtfs-realtime-bindings==1.0.0
gunicorn==22.0.0
h11==0.14.0
h2==4.1.0
haystack-ai==2.5.0
haystack-experimental==0.1.1
holoviews==1.19.1
hpack==4.0.0
html2text==2024.2.26
html5lib==1.1
httpcore==1.0.5
httplib2==0.22.0
httptools==0.6.1
httpx==0.27.2
httpx-sse==0.4.0
huggingface-hub==0.24.7
humanfriendly==10.0
humanize==4.10.0
hvplot==0.10.0
hydra-core==1.3.2
Hypercorn==0.17.3
hyperframe==6.0.1
idna==3.8
ijson==3.3.0
imageio==2.34.1
importlib_metadata==7.1.0
importlib_resources==6.4.4
inflate64==1.0.0
inflection==0.5.1
iniconfig==2.0.0
instructor==1.3.3
iopath==0.1.9
ipykernel==6.29.4
ipython==8.24.0
ipywidgets==8.1.3
isodate==0.6.1
isoduration==20.11.0
itsdangerous==2.2.0
jaraco.context==6.0.1
jedi==0.19.1
Jinja2==3.1.4
jiter==0.4.2
jmespath==1.0.1
joblib==1.4.2
jq==1.8.0
json5==0.9.25
json_repair==0.25.3
jsonlines==4.0.0
jsonpatch==1.33
jsonpath-python==1.0.6
jsonpointer==2.4
jsonref==1.1.0
jsonschema==4.22.0
jsonschema-specifications==2023.12.1
jupyter-events==0.10.0
jupyter-lsp==2.2.5
jupyter_client==8.6.1
jupyter_core==5.7.2
jupyter_server==2.14.0
jupyter_server_terminals==0.5.3
jupyterlab==4.1.8
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.1
jupyterlab_widgets==3.0.11
kaleido==0.2.1
kiwisolver==1.4.5
kubernetes==30.1.0
lancedb==0.5.7
langchain==0.2.15
langchain-anthropic==0.1.23
langchain-astradb==0.3.3
langchain-aws==0.1.17
langchain-chroma==0.1.3
langchain-cohere==0.1.9
langchain-community==0.2.15
langchain-core==0.2.37
langchain-experimental==0.0.61
langchain-google-calendar-tools==0.0.1
langchain-google-community==1.0.7
langchain-google-genai==1.0.8
langchain-google-vertexai==1.0.7
langchain-groq==0.1.6
langchain-huggingface==0.0.3
langchain-milvus==0.1.4
langchain-mistralai==0.1.10
langchain-mongodb==0.1.8
langchain-nvidia-ai-endpoints==0.1.6
langchain-openai==0.1.22
langchain-pinecone==0.1.2
langchain-text-splitters==0.2.2
langchainhub==0.1.21
langcodes==3.4.0
langdetect==1.0.9
langflow==1.0.17
langflow-base==0.0.95
langfuse==2.50.3
langgraph==0.2.15
langgraph-checkpoint==1.0.8
langserve==0.2.2
langsmith==0.1.99
language_data==1.2.0
langwatch==0.1.24
layoutparser==0.3.4
lazy-imports==0.3.1
lazy_loader==0.4
librosa==0.10.2.post1
linkify-it-py==2.0.3
litellm==1.44.16
llama-cloud==0.0.15
llama-index==0.11.12
llama-index-agent-openai==0.3.4
llama-index-cli==0.3.1
llama-index-core==0.11.12
llama-index-embeddings-huggingface==0.3.1
llama-index-embeddings-ollama==0.3.0
llama-index-embeddings-openai==0.2.5
llama-index-indices-managed-llama-cloud==0.3.0
llama-index-legacy==0.9.48
llama-index-llms-anthropic==0.3.0
llama-index-llms-ollama==0.3.1
llama-index-llms-openai==0.2.9
llama-index-multi-modal-llms-openai==0.2.0
llama-index-program-openai==0.2.0
llama-index-question-gen-openai==0.2.0
llama-index-readers-file==0.2.0
llama-index-readers-llama-parse==0.3.0
llama-index-readers-milvus==0.2.0
llama-index-vector-stores-milvus==0.2.4
llama-parse==0.5.6
llamaindex-py-client==0.1.19
llvmlite==0.43.0
loguru==0.7.2
lsprotocol==2023.0.1
lxml==5.2.1
magicattr==0.1.6
Mako==1.3.5
marisa-trie==1.2.0
Markdown==3.7
markdown-it-py==3.0.0
MarkupSafe==2.1.5
marshmallow==3.22.0
matplotlib==3.8.4
matplotlib-inline==0.1.7
mdit-plain==1.0.1
mdit-py-plugins==0.4.1
mdurl==0.1.2
mem0ai==0.0.20
metal_sdk==2.5.1
metaphor-python==0.1.23
milvus-haystack==0.0.10
milvus-lite==2.4.10
milvus-model==0.2.3
minijinja==2.0.1
minio==7.2.8
mistral_common==1.4.3
mistune==3.0.2
mmh3==4.1.0
mongoengine==0.24.2
monotonic==1.6
more-itertools==10.3.0
motor==3.5.1
mpmath==1.3.0
msgpack==1.0.8
multidict==6.1.0
multiprocess==0.70.16
multitasking==0.0.11
multivolumefile==0.2.3
murmurhash==1.0.10
mutagen==1.47.0
mypy-extensions==1.0.0
nanoid==2.0.0
narwhals==1.5.5
nbclient==0.10.0
nbconvert==7.16.4
nbformat==5.10.4
nest-asyncio==1.6.0
networkx==3.3
ninja==1.11.1.1
nltk==3.9.1
nodeenv==1.9.1
notebook_shim==0.2.4
numba==0.60.0
numexpr==2.10.1
numpy==1.26.4
oauthlib==3.2.2
ollama==0.3.1
ollama-haystack==0.0.7
omegaconf==2.3.0
onnxruntime==1.18.0
openai==1.44.0
opencv-python==4.10.0.84
opencv-python-headless==4.10.0.84
openpyxl==3.1.5
opentelemetry-api==1.25.0
opentelemetry-exporter-otlp-proto-common==1.25.0
opentelemetry-exporter-otlp-proto-grpc==1.25.0
opentelemetry-exporter-otlp-proto-http==1.25.0
opentelemetry-exporter-prometheus==0.46b0
opentelemetry-instrumentation==0.46b0
opentelemetry-instrumentation-asgi==0.46b0
opentelemetry-instrumentation-fastapi==0.46b0
opentelemetry-proto==1.25.0
opentelemetry-sdk==1.25.0
opentelemetry-semantic-conventions==0.46b0
opentelemetry-util-http==0.46b0
optimum==1.21.2
optuna==4.0.0
ordered-set==4.1.0
orjson==3.10.0
outcome==1.3.0.post0
overrides==7.7.0
packaging==24.1
pandas==2.2.2
pandocfilters==1.5.1
panel==1.4.5
param==2.1.1
parameterized==0.9.0
paramiko==3.4.1
parso==0.8.4
passlib==1.7.4
pathspec==0.12.1
pdf2image==1.17.0
pdf2img==0.1.2
pdfminer.six==20231228
pdfplumber==0.11.4
peewee==3.17.6
peft==0.12.0
pexpect==4.9.0
pgvector==0.2.5
phidata==2.4.22
pillow==10.4.0
pinecone-client==3.2.2
pinecone-plugin-inference==1.0.3
pinecone-plugin-interface==0.0.7
platformdirs==4.2.1
plotly==5.24.0
pluggy==1.5.0
pooch==1.8.2
portalocker==2.10.1
postgrest==0.16.11
posthog==3.5.0
pprintpp==0.4.0
preshed==3.0.9
priority==2.0.0
prometheus_client==0.20.0
prompt-toolkit==3.0.43
proto-plus==1.24.0
protobuf==4.25.5
psutil==5.9.8
psycopg==3.1.9
psycopg2-binary==2.9.9
ptyprocess==0.7.0
pulsar-client==3.5.0
pure-eval==0.2.2
py==1.11.0
py-cpuinfo==9.0.0
py7zr==0.22.0
pyarrow==15.0.2
pyarrow-hotfix==0.6
pyasn1==0.6.0
pyasn1_modules==0.4.0
pyautogen==0.2.35
pybcj==1.0.2
pyclipper==1.3.0.post5
pycocotools==2.0.8
pycountry==24.6.1
pycparser==2.22
pycryptodome==3.20.0
pycryptodomex==3.20.0
pydantic==2.8.2
pydantic-settings==2.3.4
pydantic_core==2.20.1
pydash==8.0.3
pydeck==0.9.1
pydot==3.0.1
Pygments==2.18.0
PyJWT==2.9.0
pylance==0.9.18
pymilvus==2.4.6
pymongo==4.8.0
PyNaCl==1.5.0
pyopensky==2.9
pyparsing==3.1.2
pypdf==4.2.0
PyPDF2==3.0.1
pypdfium2==4.30.0
pyperclip==1.9.0
PyPika==0.48.9
pyppmd==1.1.0
pyproject-toml==0.0.10
pyproject_hooks==1.1.0
pyright==1.1.379
pysbd==0.3.4
Pysher==1.0.8
PySocks==1.7.1
pytest==8.3.2
python-bidi==0.6.0
python-dateutil==2.9.0.post0
python-docx==1.1.2
python-dotenv==1.0.1
python-engineio==4.9.1
python-iso639==2024.4.27
python-jose==3.3.0
python-json-logger==2.0.7
python-lsp-jsonrpc==1.1.2
python-magic==0.4.27
python-multipart==0.0.7
python-pptx==0.6.23
python-socketio==5.11.3
pytube==15.0.0
pytz==2024.2
pyviz_comms==3.0.3
PyYAML==6.0.2
pyzmq==26.0.3
pyzstd==0.16.1
qdrant-client==1.11.1
qianfan==0.3.5
qwen-vl-utils==0.0.4
radient==2024.8.19
ragas==0.1.16
rapidfuzz==3.9.6
rarfile==4.2
ratelimiter==1.2.0.post0
realtime==2.0.2
referencing==0.35.1
regex==2024.9.11
requests==2.32.3
requests-futures==1.0.1
requests-oauthlib==2.0.0
requests-toolbelt==1.0.0
retry==0.9.2
retrying==1.3.4
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.7.1
rpds-py==0.18.1
rsa==4.9
rss2newsletter==1.0.5
ruff==0.6.3
rule-based-retrieval==0.1.4
s3transfer==0.10.1
safetensors==0.4.5
schema==0.7.7
scikit-image==0.23.2
scikit-learn==1.5.1
scipy==1.13.0
seaborn==0.13.2
selenium==4.24.0
semver==3.0.2
Send2Trash==1.8.3
sentence-transformers==3.0.1
sentencepiece==0.2.0
sentry-sdk==2.13.0
setuptools==74.1.2
sgmllib3k==1.0.0
shapely==2.0.6
shellingham==1.5.4
sherlock-project==0.15.0
simple-websocket==1.0.0
six==1.16.0
slack_bolt==1.20.0
slack_sdk==3.27.2
smart-open==7.0.4
smmap==5.0.1
sniffio==1.3.1
sortedcontainers==2.4.0
soundfile==0.12.1
soupsieve==2.5
soxr==0.5.0
spacy==3.7.6
spacy-legacy==3.0.12
spacy-loggers==1.0.5
spider-client==0.0.27
SQLAlchemy==2.0.34
sqlmodel==0.0.18
srsly==2.4.8
sse-starlette==0.10.3
sseclient-py==1.8.0
st-milvus-connection==0.0.4
stack-data==0.6.3
starlette==0.37.2
stem==1.8.2
storage3==0.7.7
strawberry-graphql==0.138.1
streamlit==1.38.0
StrEnum==0.4.15
striprtf==0.0.26
structlog==24.4.0
sumy==0.11.0
suno-bark @ git+https://github.com/suno-ai/bark.git@f4f32d4cd480dfec1c245d258174bc9bde3c2148
supabase==2.7.4
supafunc==0.5.1
sympy==1.13.2
tabulate==0.9.0
tavily-python==0.4.0
tenacity==8.3.0
tensorboard==2.17.1
tensorboard-data-server==0.7.2
termcolor==2.4.0
terminado==0.18.1
texttable==1.7.0
thinc==8.2.5
threadpoolctl==3.5.0
tifffile==2024.5.3
tiktoken==0.7.0
timm==1.0.9
tinycss2==1.3.0
tokenizers==0.19.1
toml==0.10.2
tomli==2.0.1
torch==2.4.0
torchaudio==2.4.0
torchvision==0.19.0
tornado==6.4
tqdm==4.66.5
traitlets==5.14.3
transformers==4.44.2
tree-sitter==0.23.0
tree-sitter-python==0.23.2
trino==0.329.0
trio==0.26.2
trio-websocket==0.11.1
typer==0.12.3
types-cachetools==5.5.0.20240820
types-python-dateutil==2.9.0.20240316
types-requests==2.32.0.20240712
typing-inspect==0.9.0
typing_extensions==4.12.2
tzdata==2024.1
tzlocal==5.2
uc-micro-py==1.0.3
ujson==5.10.0
ultralytics==8.2.82
ultralytics-thop==2.0.5
uncurl==0.0.11
universal-analytics-python3==1.1.1
unstructured==0.14.10
unstructured-client==0.25.5
upstash-vector==0.4.0
uri-template==1.3.0
uritemplate==4.1.1
urllib3==2.2.3
uuid6==2024.1.12
uvicorn==0.30.1
uvloop==0.19.0
validators==0.33.0
voxel51-eta==0.12.7
wasabi==1.1.3
watchdog==5.0.2
watchfiles==0.22.0
wcwidth==0.2.13
weasel==0.4.1
weaviate-client==4.7.1
webcolors==1.13
webencodings==0.5.1
websocket-client==1.8.0
websockets==12.0
Werkzeug==3.0.4
wheel==0.44.0
widgetsnbextension==4.0.11
wikipedia==1.4.0
Wikipedia-API==0.6.0
wolframalpha==5.1.3
wrapt==1.16.0
wsproto==1.2.0
xformer==1.0.1
xformers==0.0.23
XlsxWriter==3.2.0
xmltodict==0.13.0
xxhash==3.5.0
xyzservices==2024.6.0
yacs==0.1.8
yarl==1.11.1
yfinance==0.2.43
youtube-transcript-api==0.6.2
yt-dlp==2024.8.6
zep-python==2.0.0rc6
zipp==3.20.1
```

### Reproduction Steps

poetry install

or 
pip3 install mistral_inference

### Expected Behavior

compile and work

### Additional Context

It fails on build of xformers

env/lib/python3.12/site-packages/torch/include/THC -I/Users/timothyspann/Downloads/code/milvusvenv/include -I/opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c -c /private/var/folders/c2/6wq9klzn19d97gvw8f8j1jdr0000gn/T/pip-install-p9bq7hp4/xformers_6ffdc41865e543c99f124e7bdc9bacd2/xformers/csrc/attention/sddmm.cpp -o /private/var/folders/c2/6wq9klzn19d97gvw8f8j1jdr0000gn/T/pip-install-p9bq7hp4/xformers_6ffdc41865e543c99f124e7bdc9bacd2/build/temp.macosx-13.0-arm64-cpython-312/xformers/csrc/attention/sddmm.o -O3 -std=c++17 -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_clang"' '-DPYBIND11_STDLIB="_libcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1002"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
      clang: error: unsupported option '-fopenmp'
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/Users/timothyspann/Downloads/code/milvusvenv/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 2105, in _run_ninja_build
          subprocess.run(
        File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/c2/6wq9klzn19d97gvw8f8j1jdr0000gn/T/pip-install-p9bq7hp4/xformers_6ffdc41865e543c99f124e7bdc9bacd2/setup.py", line 680, in <module>
          setuptools.setup(
        File "/Users/timothyspann/Downloads/code/milvusvenv/lib/python3.12/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/timothyspann/Downloads/code/milvusvenv/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/Users/timothyspann/Downloads/code/milvusvenv/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/Users/timothyspann/Downloads/code/milvusvenv/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/Users/timothyspann/Downloads/code/milvusvenv/lib/python3.12/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/Users/timothyspann/Downloads/code/milvusvenv/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/Users/timothyspann/Downloads/code/milvusvenv/lib/python3.12/site-packages/setuptools/command/bdist_wheel.py", line 384, in run
          self.run_command("build")
        File "/Users/timothyspann/Downloads/code/milvusvenv/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/Users/timothyspann/Downloads/code/milvusvenv/lib/python3.12/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/Users/timothyspann/Downloads/code/milvusvenv/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/Users/timothyspann/Downloads/code/milvusvenv/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/Users/timothyspann/Downloads/code/milvusvenv/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/Users/timothyspann/Downloads/code/milvusvenv/lib/python3.12/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/Users/timothyspann/Downloads/code/milvusvenv/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/Users/timothyspann/Downloads/code/milvusvenv/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 98, in run
          _build_ext.run(self)
        File "/Users/timothyspann/Downloads/code/milvusvenv/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/private/var/folders/c2/6wq9klzn19d97gvw8f8j1jdr0000gn/T/pip-install-p9bq7hp4/xformers_6ffdc41865e543c99f124e7bdc9bacd2/setup.py", line 637, in build_extensions
          super().build_extensions()
        File "/Users/timothyspann/Downloads/code/milvusvenv/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 866, in build_extensions
          build_ext.build_extensions(self)
        File "/Users/timothyspann/Downloads/code/milvusvenv/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
          self._build_extensions_serial()
        File "/Users/timothyspann/Downloads/code/milvusvenv/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
          self.build_extension(ext)
        File "/Users/timothyspann/Downloads/code/milvusvenv/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 263, in build_extension
          _build_ext.build_extension(self, ext)
        File "/Users/timothyspann/Downloads/code/milvusvenv/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 557, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/timothyspann/Downloads/code/milvusvenv/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 679, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/Users/timothyspann/Downloads/code/milvusvenv/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 1785, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/Users/timothyspann/Downloads/code/milvusvenv/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 2121, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for xformers
  Running setup.py clean for xformers
Failed to build xformers
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (xformers)

**Comment by james-relata** [comment]
I think this is due to xformers not wanting to provide Apple Silicon support to focus on CUDA - https://github.com/facebookresearch/xformers/issues/858

**Comment by juliendenize** [comment]
Hi! We're archiving this repository as it's no longer actively maintained, and therefore this issue is being closed.
